version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"    
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  app:
    build: .
    image: myapp:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
    volumes:
      - .:/app
      - ./config/.env:/app/config/.env:ro
    command: >
      sh -c "python -m database.database_init &&
             python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload --env-file config/.env"

volumes:
  pgdata:
